version: "3.8"
services:
  microblog:
    build: .
    container_name: microblog_compose
    image: microblog:compose
    environment:
      - DATABASE_URL=mysql+pymysql://microblog:microblog_pass@dbserver/microblog
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    ports:
      - '8000:5000'
    links:
      - mysql:dbserver
      - elasticsearch:elasticsearch
    depends_on:
      - mysql
      - elasticsearch
  mysql:
    container_name: mysql
    image: mysql/mysql-server:5.7
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=microblog
      - MYSQL_USER=microblog
      - MYSQL_PASSWORD=microblog_pass
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.6.2
    environment:
      - discovery.type=single-node
    ports:
      - '9200:9200'
      - '9300:9300'
