version: "3.8"
services:
  microblog:
    build: .
    container_name: microblog
    image: microblog:latest
    environment:
      - DATABASE_URL=mysql+pymysql://microblog:microblog_pass@dbserver/microblog
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - REDIS_URL=redis://redis-server:6379/0
    ports:
      - '8000:5000'
    links:
      - mysql:dbserver
      - elasticsearch:elasticsearch
      - redis:redis-server
  mysql:
    container_name: mysql
    image: mysql/mysql-server:5.7
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=microblog
      - MYSQL_USER=microblog
      - MYSQL_PASSWORD=microblog_pass
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.6.2
    environment:
      - discovery.type=single-node
    ports:
      - '9200:9200'
      - '9300:9300'
  redis:
    container_name: redis
    image: redis:3-alpine
    ports:
      - '6379:6379'
  rq-worker:
    container_name: rq-worker
    image: microblog:latest
    environment:
      - DATABASE_URL=mysql+pymysql://microblog:microblog_pass@dbserver/microblog
      - REDIS_URL=redis://redis-server:6379/0
      - MAIL_SERVER=127.0.0.1
      - MAIL_PORT=8025
    links:
      - mysql:dbserver
      - redis:redis-server
    entrypoint: ['rq']
    command: ["worker", "-u", "redis://redis-server:6379/0", "microblog-tasks"]
    depends_on:
      - microblog
